# Generated by Django 3.2.9 on 2021-11-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('FT', 'FT Employee'), ('NT', 'Contractor/Intern')], default='FT', max_length=25)),
                ('title', models.CharField(max_length=35)),
                ('department', models.CharField(choices=[('P', 'Product'), ('C', 'Consumer'), ('O', 'Operations'), ('S', 'SG Enterprise'), ('PO', 'People Ops'), ('F', 'Finance'), ('BS', 'Business Systems'), ('SC', 'Security & Compliance')], max_length=25)),
                ('sub_department', models.CharField(blank=True, max_length=25, null=True)),
                ('team', models.CharField(blank=True, max_length=25, null=True)),
                ('sub_team', models.CharField(blank=True, max_length=25, null=True)),
                ('reports_to', models.CharField(blank=True, max_length=25, null=True)),
                ('location', models.CharField(max_length=25)),
                ('peronsal_email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('manager', models.BooleanField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='date of last edit')),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.sheet')),
            ],
        ),
    ]
