# Generated by Django 3.1.7 on 2021-03-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('char_sheet', models.TextField()),
                ('section1', models.TextField()),
                ('section2', models.TextField()),
                ('section3', models.TextField()),
                ('section4', models.TextField()),
                ('section5', models.TextField()),
                ('section6', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('edit_date', models.DateTimeField(verbose_name='date of last edit')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
