# Generated by Django 3.2.9 on 2021-11-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='peronsal_email',
            new_name='personal_email',
        ),
    ]
