# Generated by Django 3.1.7 on 2021-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210316_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of last edit'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
