# Generated by Django 3.2.9 on 2021-11-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_peronsal_email_sheet_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='employment_type',
            field=models.CharField(choices=[('FT', 'FT Employee'), ('NT', 'Contractor / Intern')], default='FT', max_length=25),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
