# Generated by Django 3.1.7 on 2021-03-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210317_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='t_affil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='t_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='t_bday',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='t_bplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='t_debut',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='t_form',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
