# Generated by Django 3.1.7 on 2021-03-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210317_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='t_affil',
        ),
    ]
