# Generated by Django 3.1.7 on 2021-03-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sheet_t_affil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='t_img',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images/'),
        ),
    ]
