# Generated by Django 3.1.7 on 2021-03-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210317_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='t_img',
            field=models.ImageField(null=True, upload_to='templates/images/'),
        ),
    ]
