# Generated by Django 3.1.7 on 2021-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210318_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='t_form',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
