# Generated by Django 3.1.7 on 2021-03-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210318_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='t_img',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
