# Generated by Django 3.1.7 on 2021-03-21 23:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210318_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='section1',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='section2',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='section3',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='section4',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='section5',
        ),
        migrations.AddField(
            model_name='sheet',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
